### ISSUE TITLE
Unable to run experiment results

### ISSUE THREAD

**Issue by fbllupup** [BaoqianWang/Batch-Processing-Coded-Computation#1]
hmcc.py and bpcc.py can only run until the "print('Waiting results')" [,but](url) the program does not report an error and cannot return to the decoding time. I am very interested in this paper of yours. Can you answer my doubts?

**Comment by BaoqianWang** [comment]
Hello, 
are you using the default configured parameters? If not, could you provide your configured parameters so that I can reproduce the bug? Thanks

**Comment by fbllupup** [comment]
I used your default parameters. bpcc.py can run normally. hcmm.py has been running all the time, but it has not been able to run the results. Thank you for your patience in your busy schedule

**Comment by BaoqianWang** [comment]
Hello, 
I checked the code. It can run in my computer. I ran the hcmm.py using 'mpirun -np 4 python3 hcmm.py'. Are you using the similar command?

**Comment by fbllupup** [comment]
I don't worry about hmcc.py anymore. I want to ask you a new question. When I increase the number of nodes to 10, the following error message appears，but I have no problem using the default parameters
Traceback (most recent call last):
  File "bpcc.py", line 83, in <module>
    data = req.wait()
  File "mpi4py\MPI\Request.pyx", line 266, in mpi4py.MPI.Request.wait
  File "mpi4py\MPI\msgpickle.pxi", line 457, in mpi4py.MPI.PyMPI_wait
  File "mpi4py\MPI\msgpickle.pxi", line 443, in mpi4py.MPI.PyMPI_load
  File "mpi4py\MPI\msgpickle.pxi", line 152, in mpi4py.MPI.pickle_load
  File "mpi4py\MPI\msgpickle.pxi", line 141, in mpi4py.MPI.cloads
_pickle.UnpicklingError: invalid load key, '\xa8'.


Here's mine computation_configuration.json
{
"num_iteration": 100,
"A_dimension": [20000, 4000],
"A_hat_dimension": [40000, 4000],
"worker_node_load_index": [[0, 4000], [4000, 8000], [8000, 12000], [12000, 16000], [16000,20000], [20000, 24000], [24000, 28000], [28000, 32000], [32000, 36000], [36000, 40000]],
"worker_batch_p_value": [4000, 4000, 4000, 4000, 4000, 4000, 4000, 4000, 4000, 4000],
"interval": 100,
"delta": 0.01,
"c": 3.4
}

**Comment by BaoqianWang** [comment]
Hello, 

I checked the issue. It seems to be related to 'isend' function dealing with large block data. I haven't found a good solution to it. Smaller size  should work.

**Comment by fbllupup** [comment]
Hello, maybe I have solved this problem, probably the problem of json file, but LT_ code has a problem I can't solve
 File "E:\Python\Codes\LT_code\LT_code.py", line 102, in lt_decode
    index = symbol.neighbors[i]
IndexError: list index out of range

**Comment by BaoqianWang** [comment]
Hello,
I checked the code and didn't find the line, 
index = symbol.neighbors[i],
Instead, I found 
index = symbol.neighbors[0]

**Comment by wang-ting000** [comment]
> I don't worry about hmcc.py anymore. I want to ask you a new question. When I increase the number of nodes to 10, the following error message appears，but I have no problem using the default parameters Traceback (most recent call last): File "bpcc.py", line 83, in data = req.wait() File "mpi4py\MPI\Request.pyx", line 266, in mpi4py.MPI.Request.wait File "mpi4py\MPI\msgpickle.pxi", line 457, in mpi4py.MPI.PyMPI_wait File "mpi4py\MPI\msgpickle.pxi", line 443, in mpi4py.MPI.PyMPI_load File "mpi4py\MPI\msgpickle.pxi", line 152, in mpi4py.MPI.pickle_load File "mpi4py\MPI\msgpickle.pxi", line 141, in mpi4py.MPI.cloads _pickle.UnpicklingError: invalid load key, '\xa8'.
> 
> Here's mine computation_configuration.json { "num_iteration": 100, "A_dimension": [20000, 4000], "A_hat_dimension": [40000, 4000], "worker_node_load_index": [[0, 4000], [4000, 8000], [8000, 12000], [12000, 16000], [16000,20000], [20000, 24000], [24000, 28000], [28000, 32000], [32000, 36000], [36000, 40000]], "worker_batch_p_value": [4000, 4000, 4000, 4000, 4000, 4000, 4000, 4000, 4000, 4000], "interval": 100, "delta": 0.01, "c": 3.4 }

hi,I'm really sorry to disturb you, but I'm wondering how did you solve the problem of hcmm.py not printing, cause I'm facing the problem too. Thanks for your reply.
